name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          
          echo "${{ secrets.DATABASE_PROPERTIES }}" >> ./application.properties

      - name: Build Test with Gradle
        run: ./gradlew --info